import {
  COMPANY_TYPES,
  CONTRACT_STATUSES,
  CONTRACT_TYPES,
  DELIVERY_STATUSES,
  EVENT_STATUSES,
  GATE_PASS_TYPES,
  INVOICE_STATUSES,
  PAYMENT_STATUSES,
  PO_STATUSES,
  PRIORITIES,
  QUOTATION_STATUSES,
  RFQ_STATUSES,
  TASK_STATUSES,
  TICKET_CATEGORIES,
  TICKET_STATUSES,
  VAT_STATUSES,
  ZONE_TYPES,
} from "@/lib/constants"

export type FieldType = "text" | "textarea" | "number" | "date" | "select" | "email" | "lookup" | "lines" | "vendors"

export type FieldConfig = {
  name: string
  label: string
  type: FieldType
  options?: string[]
  lookup?: "vendors" | "events" | "categories" | "terms" | "emirates" | "users" | "documentTypes" | "roles"
  required?: boolean
  asArray?: boolean
}

export type ColumnConfig = {
  key: string
  label: string
  kind?: "text" | "status" | "date" | "money"
}

export type ModuleConfig = {
  key: string
  title: string
  description: string
  api: string
  permission: string
  statuses?: string[]
  columns: ColumnConfig[]
  fields: FieldConfig[]
  creatable?: boolean
  vendorCreatable?: boolean
  editable?: boolean
  deletable?: boolean
  vendorEditable?: boolean
}

const opts = (values: readonly string[]) => [...values]

export const modules: Record<string, ModuleConfig> = {
  vendors: {
    key: "vendors",
    title: "Vendors",
    description: "Invite a company with an email address. Extra details are optional and can be completed by the vendor.",
    api: "/api/vendors",
    permission: "vendors",
    statuses: ["DRAFT", "SUBMITTED", "UNDER_REVIEW", "CHANGES_REQUESTED", "APPROVED", "ACTIVE", "SUSPENDED", "REJECTED"],
    columns: [
      { key: "vendorCode", label: "ID" },
      { key: "legalName", label: "Company" },
      { key: "emirate", label: "Emirate" },
      { key: "status", label: "Status", kind: "status" },
      { key: "complianceScore", label: "Compliance" },
    ],
    fields: [
      { name: "loginEmail", label: "Login email", type: "email", required: true },
      { name: "legalName", label: "Legal company name", type: "text" },
      { name: "tradeName", label: "Trade name", type: "text" },
      { name: "tradeLicenseNumber", label: "Trade license number", type: "text" },
      { name: "licenseAuthority", label: "Issuing authority", type: "text" },
      { name: "companyType", label: "Company type", type: "select", options: opts(COMPANY_TYPES) },
      { name: "zoneType", label: "Mainland / free zone", type: "select", options: opts(ZONE_TYPES) },
      { name: "emirate", label: "Emirate", type: "lookup", lookup: "emirates" },
      { name: "businessActivity", label: "Business activity", type: "text" },
      { name: "address", label: "Office address", type: "textarea" },
      { name: "website", label: "Website", type: "text" },
      { name: "trn", label: "TRN", type: "text" },
      { name: "vatStatus", label: "VAT status", type: "select", options: opts(VAT_STATUSES) },
      { name: "categoryIds", label: "Category", type: "lookup", lookup: "categories", asArray: true },
      { name: "paymentTermId", label: "Payment terms", type: "lookup", lookup: "terms" },
      { name: "bankName", label: "Bank name", type: "text" },
      { name: "iban", label: "IBAN", type: "text" },
      { name: "accountName", label: "Account name", type: "text" },
    ],
    creatable: true,
    editable: true,
    deletable: true,
  },
  applications: {
    key: "applications",
    title: "Applications",
    description: "Registrations waiting for review.",
    api: "/api/vendor-applications",
    permission: "vendors",
    columns: [
      { key: "vendorCode", label: "ID" },
      { key: "legalName", label: "Company" },
      { key: "emirate", label: "Emirate" },
      { key: "status", label: "Status", kind: "status" },
      { key: "submittedAt", label: "Submitted", kind: "date" },
    ],
    fields: [],
  },
  events: {
    key: "events",
    title: "Events",
    description: "Exhibitions, conferences, and hospitality programmes.",
    api: "/api/events",
    permission: "events",
    statuses: opts(EVENT_STATUSES),
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Event" },
      { key: "client", label: "Client" },
      { key: "emirate", label: "Emirate" },
      { key: "status", label: "Status", kind: "status" },
      { key: "startDate", label: "Starts", kind: "date" },
    ],
    fields: [
      { name: "name", label: "Event name", type: "text", required: true },
      { name: "client", label: "Client", type: "text" },
      { name: "venue", label: "Venue", type: "text" },
      { name: "emirate", label: "Emirate", type: "lookup", lookup: "emirates" },
      { name: "eventType", label: "Event type", type: "text" },
      { name: "startDate", label: "Start date", type: "date" },
      { name: "endDate", label: "End date", type: "date" },
      { name: "status", label: "Status", type: "select", options: opts(EVENT_STATUSES) },
      { name: "description", label: "Description", type: "textarea" },
    ],
    creatable: true,
    editable: true,
    deletable: true,
  },
  rfqs: {
    key: "rfqs",
    title: "Requests for quotation",
    description: "Invite vendors to price a requirement.",
    api: "/api/rfqs",
    permission: "rfqs",
    statuses: opts(RFQ_STATUSES),
    columns: [
      { key: "number", label: "RFQ" },
      { key: "title", label: "Requirement" },
      { key: "category", label: "Category" },
      { key: "status", label: "Status", kind: "status" },
      { key: "deadline", label: "Deadline", kind: "date" },
    ],
    fields: [
      { name: "title", label: "Requirement", type: "text", required: true },
      { name: "eventId", label: "Event", type: "lookup", lookup: "events" },
      { name: "category", label: "Category", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "quantity", label: "Quantity", type: "number" },
      { name: "unit", label: "Unit", type: "text" },
      { name: "deliveryLocation", label: "Delivery location", type: "text" },
      { name: "requiredDate", label: "Required date", type: "date" },
      { name: "deadline", label: "Submission deadline", type: "date" },
      { name: "status", label: "Status", type: "select", options: opts(RFQ_STATUSES) },
      { name: "vendorIds", label: "Invite vendors", type: "vendors" },
    ],
    creatable: true,
    editable: true,
  },
  quotations: {
    key: "quotations",
    title: "Quotations",
    description: "Line-item prices, VAT, and comparison.",
    api: "/api/quotations",
    permission: "quotations",
    statuses: opts(QUOTATION_STATUSES),
    columns: [
      { key: "number", label: "Quote" },
      { key: "vendor.legalName", label: "Vendor" },
      { key: "rfq.title", label: "RFQ" },
      { key: "total", label: "Total", kind: "money" },
      { key: "status", label: "Status", kind: "status" },
    ],
    fields: [
      { name: "vendorId", label: "Vendor", type: "lookup", lookup: "vendors", required: true },
      { name: "rfqId", label: "RFQ", type: "text" },
      { name: "discount", label: "Discount", type: "number" },
      { name: "deliveryCharges", label: "Delivery charges", type: "number" },
      { name: "notes", label: "Notes", type: "textarea" },
      { name: "items", label: "Line items", type: "lines", required: true },
    ],
    creatable: true,
    vendorCreatable: true,
    editable: true,
    vendorEditable: true,
  },
  "purchase-orders": {
    key: "purchase-orders",
    title: "Purchase orders",
    description: "Commercial orders issued to vendors.",
    api: "/api/purchase-orders",
    permission: "purchaseOrders",
    statuses: opts(PO_STATUSES),
    columns: [
      { key: "number", label: "PO" },
      { key: "vendor.legalName", label: "Vendor" },
      { key: "event.name", label: "Event" },
      { key: "total", label: "Total", kind: "money" },
      { key: "status", label: "Status", kind: "status" },
    ],
    fields: [
      { name: "vendorId", label: "Vendor", type: "lookup", lookup: "vendors", required: true },
      { name: "eventId", label: "Event", type: "lookup", lookup: "events" },
      { name: "quotationId", label: "Quotation ID", type: "text" },
      { name: "paymentTermId", label: "Payment terms", type: "lookup", lookup: "terms" },
      { name: "deliveryDate", label: "Delivery date", type: "date" },
      { name: "status", label: "Status", type: "select", options: opts(PO_STATUSES) },
      { name: "terms", label: "Terms", type: "textarea" },
      { name: "items", label: "Line items", type: "lines" },
    ],
    creatable: true,
    editable: true,
  },
  contracts: {
    key: "contracts",
    title: "Contracts",
    description: "NDAs, vendor agreements, and event contracts.",
    api: "/api/contracts",
    permission: "contracts",
    statuses: opts(CONTRACT_STATUSES),
    columns: [
      { key: "number", label: "Contract" },
      { key: "title", label: "Title" },
      { key: "vendor.legalName", label: "Vendor" },
      { key: "type", label: "Type", kind: "status" },
      { key: "status", label: "Status", kind: "status" },
      { key: "endDate", label: "Ends", kind: "date" },
    ],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "type", label: "Type", type: "select", options: opts(CONTRACT_TYPES), required: true },
      { name: "vendorId", label: "Vendor", type: "lookup", lookup: "vendors", required: true },
      { name: "eventId", label: "Event", type: "lookup", lookup: "events" },
      { name: "startDate", label: "Start", type: "date" },
      { name: "endDate", label: "End", type: "date" },
      { name: "renewalDate", label: "Renewal", type: "date" },
      { name: "value", label: "Value", type: "number" },
      { name: "status", label: "Status", type: "select", options: opts(CONTRACT_STATUSES) },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    creatable: true,
    editable: true,
  },
  documents: {
    key: "documents",
    title: "Documents",
    description: "Licences, certificates, and event files.",
    api: "/api/vendor-documents",
    permission: "documents",
    statuses: ["PENDING", "UNDER_REVIEW", "APPROVED", "REJECTED", "EXPIRING_SOON", "EXPIRED"],
    columns: [
      { key: "title", label: "Document" },
      { key: "vendor.legalName", label: "Vendor" },
      { key: "documentType.name", label: "Type" },
      { key: "status", label: "Status", kind: "status" },
      { key: "expiryDate", label: "Expires", kind: "date" },
    ],
    fields: [
      { name: "vendorId", label: "Vendor", type: "lookup", lookup: "vendors", required: true },
      { name: "documentTypeId", label: "Type", type: "lookup", lookup: "documentTypes" },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "issueDate", label: "Issue date", type: "date" },
      { name: "expiryDate", label: "Expiry date", type: "date" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    creatable: true,
    vendorCreatable: true,
  },
  compliance: {
    key: "compliance",
    title: "Compliance",
    description: "Expired and expiring documents.",
    api: "/api/vendor-documents",
    permission: "documents",
    columns: [
      { key: "title", label: "Document" },
      { key: "vendor.legalName", label: "Vendor" },
      { key: "status", label: "Status", kind: "status" },
      { key: "expiryDate", label: "Expires", kind: "date" },
    ],
    fields: [],
  },
  tasks: {
    key: "tasks",
    title: "Tasks",
    description: "Work assigned against a vendor or event.",
    api: "/api/tasks",
    permission: "tasks",
    statuses: opts(TASK_STATUSES),
    columns: [
      { key: "title", label: "Task" },
      { key: "vendor.legalName", label: "Vendor" },
      { key: "priority", label: "Priority", kind: "status" },
      { key: "status", label: "Status", kind: "status" },
      { key: "dueDate", label: "Due", kind: "date" },
    ],
    fields: [
      { name: "title", label: "Task", type: "text", required: true },
      { name: "vendorId", label: "Vendor", type: "lookup", lookup: "vendors" },
      { name: "eventId", label: "Event", type: "lookup", lookup: "events" },
      { name: "assigneeId", label: "Assigned person", type: "lookup", lookup: "users" },
      { name: "priority", label: "Priority", type: "select", options: opts(PRIORITIES) },
      { name: "dueDate", label: "Due date", type: "date" },
      { name: "status", label: "Status", type: "select", options: opts(TASK_STATUSES) },
      { name: "description", label: "Description", type: "textarea" },
    ],
    creatable: true,
    editable: true,
    vendorEditable: true,
  },
  deliveries: {
    key: "deliveries",
    title: "Deliveries",
    description: "Vehicles, materials, and proof of receipt.",
    api: "/api/deliveries",
    permission: "deliveries",
    statuses: opts(DELIVERY_STATUSES),
    columns: [
      { key: "number", label: "Delivery" },
      { key: "material", label: "Material" },
      { key: "vendor.legalName", label: "Vendor" },
      { key: "status", label: "Status", kind: "status" },
      { key: "expectedDate", label: "Expected", kind: "date" },
    ],
    fields: [
      { name: "vendorId", label: "Vendor", type: "lookup", lookup: "vendors", required: true },
      { name: "eventId", label: "Event", type: "lookup", lookup: "events" },
      { name: "material", label: "Material", type: "text", required: true },
      { name: "quantity", label: "Quantity", type: "number" },
      { name: "expectedDate", label: "Expected date", type: "date" },
      { name: "actualDate", label: "Actual date", type: "date" },
      { name: "receiver", label: "Receiver", type: "text" },
      { name: "plateNumber", label: "Vehicle plate", type: "text" },
      { name: "driverName", label: "Driver", type: "text" },
      { name: "driverMobile", label: "Driver mobile", type: "text" },
      { name: "status", label: "Status", type: "select", options: opts(DELIVERY_STATUSES) },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    creatable: true,
    vendorCreatable: true,
    editable: true,
  },
  workforce: {
    key: "workforce",
    title: "Workforce",
    description: "Vendor staff proposed for an event.",
    api: "/api/workforce",
    permission: "workforce",
    statuses: ["PENDING", "APPROVED", "REJECTED"],
    columns: [
      { key: "name", label: "Name" },
      { key: "vendor.legalName", label: "Vendor" },
      { key: "designation", label: "Designation" },
      { key: "shift", label: "Shift" },
      { key: "status", label: "Status", kind: "status" },
    ],
    fields: [
      { name: "vendorId", label: "Vendor", type: "lookup", lookup: "vendors", required: true },
      { name: "eventId", label: "Event", type: "lookup", lookup: "events" },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "mobile", label: "Mobile", type: "text" },
      { name: "designation", label: "Designation", type: "text" },
      { name: "idType", label: "ID type", type: "text" },
      { name: "idNumber", label: "ID number", type: "text" },
      { name: "shift", label: "Shift", type: "text" },
    ],
    creatable: true,
    vendorCreatable: true,
  },
  "gate-passes": {
    key: "gate-passes",
    title: "Gate passes",
    description: "QR passes for people, vehicles, and materials.",
    api: "/api/gate-passes",
    permission: "gatePasses",
    statuses: ["DRAFT", "ISSUED", "USED", "EXPIRED", "REVOKED"],
    columns: [
      { key: "code", label: "Code" },
      { key: "holderName", label: "Holder" },
      { key: "type", label: "Type", kind: "status" },
      { key: "vendor.legalName", label: "Vendor" },
      { key: "status", label: "Status", kind: "status" },
    ],
    fields: [
      { name: "type", label: "Pass type", type: "select", options: opts(GATE_PASS_TYPES), required: true },
      { name: "holderName", label: "Holder name", type: "text", required: true },
      { name: "vendorId", label: "Vendor", type: "lookup", lookup: "vendors" },
      { name: "eventId", label: "Event", type: "lookup", lookup: "events" },
      { name: "plateNumber", label: "Vehicle plate", type: "text" },
      { name: "validFrom", label: "Valid from", type: "date" },
      { name: "validTo", label: "Valid to", type: "date" },
    ],
    creatable: true,
  },
  invoices: {
    key: "invoices",
    title: "Invoices",
    description: "Vendor invoices against purchase orders.",
    api: "/api/invoices",
    permission: "invoices",
    statuses: opts(INVOICE_STATUSES),
    columns: [
      { key: "number", label: "Invoice" },
      { key: "vendor.legalName", label: "Vendor" },
      { key: "po.number", label: "PO" },
      { key: "total", label: "Total", kind: "money" },
      { key: "status", label: "Status", kind: "status" },
    ],
    fields: [
      { name: "vendorId", label: "Vendor", type: "lookup", lookup: "vendors", required: true },
      { name: "poId", label: "Purchase order ID", type: "text" },
      { name: "eventId", label: "Event", type: "lookup", lookup: "events" },
      { name: "invoiceDate", label: "Invoice date", type: "date" },
      { name: "trn", label: "TRN", type: "text" },
      { name: "notes", label: "Notes", type: "textarea" },
      { name: "items", label: "Line items", type: "lines", required: true },
    ],
    creatable: true,
    vendorCreatable: true,
    editable: true,
    vendorEditable: true,
  },
  payments: {
    key: "payments",
    title: "Payments",
    description: "Advances, balances, and due dates.",
    api: "/api/payments",
    permission: "payments",
    statuses: opts(PAYMENT_STATUSES),
    columns: [
      { key: "reference", label: "Reference" },
      { key: "vendor.legalName", label: "Vendor" },
      { key: "amount", label: "Amount", kind: "money" },
      { key: "paidAmount", label: "Paid", kind: "money" },
      { key: "status", label: "Status", kind: "status" },
      { key: "dueDate", label: "Due", kind: "date" },
    ],
    fields: [
      { name: "vendorId", label: "Vendor", type: "lookup", lookup: "vendors", required: true },
      { name: "invoiceId", label: "Invoice ID", type: "text" },
      { name: "poId", label: "PO ID", type: "text" },
      { name: "amount", label: "Amount", type: "number", required: true },
      { name: "advance", label: "Advance", type: "number" },
      { name: "paidAmount", label: "Paid", type: "number" },
      { name: "dueDate", label: "Due date", type: "date" },
      { name: "method", label: "Method", type: "text" },
      { name: "status", label: "Status", type: "select", options: opts(PAYMENT_STATUSES) },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    creatable: true,
    editable: true,
  },
  performance: {
    key: "performance",
    title: "Performance",
    description: "Scores recorded after an event.",
    api: "/api/performance",
    permission: "performance",
    columns: [
      { key: "vendor.legalName", label: "Vendor" },
      { key: "quality", label: "Quality" },
      { key: "delivery", label: "Delivery" },
      { key: "communication", label: "Communication" },
      { key: "compliance", label: "Compliance" },
      { key: "createdAt", label: "Recorded", kind: "date" },
    ],
    fields: [
      { name: "vendorId", label: "Vendor", type: "lookup", lookup: "vendors", required: true },
      { name: "eventId", label: "Event", type: "lookup", lookup: "events" },
      { name: "quality", label: "Quality (1-5)", type: "number", required: true },
      { name: "delivery", label: "Delivery (1-5)", type: "number", required: true },
      { name: "pricing", label: "Pricing (1-5)", type: "number", required: true },
      { name: "communication", label: "Communication (1-5)", type: "number", required: true },
      { name: "compliance", label: "Compliance (1-5)", type: "number", required: true },
      { name: "responsiveness", label: "Responsiveness (1-5)", type: "number", required: true },
      { name: "service", label: "Service (1-5)", type: "number", required: true },
      { name: "staff", label: "Staff (1-5)", type: "number", required: true },
      { name: "issueResolution", label: "Issue resolution (1-5)", type: "number", required: true },
      { name: "comments", label: "Comments", type: "textarea" },
    ],
    creatable: true,
  },
  tickets: {
    key: "tickets",
    title: "Support",
    description: "Questions about payments, documents, and events.",
    api: "/api/tickets",
    permission: "tickets",
    statuses: opts(TICKET_STATUSES),
    columns: [
      { key: "number", label: "Ticket" },
      { key: "subject", label: "Subject" },
      { key: "category", label: "Category", kind: "status" },
      { key: "priority", label: "Priority", kind: "status" },
      { key: "status", label: "Status", kind: "status" },
    ],
    fields: [
      { name: "vendorId", label: "Vendor", type: "lookup", lookup: "vendors" },
      { name: "category", label: "Category", type: "select", options: opts(TICKET_CATEGORIES), required: true },
      { name: "priority", label: "Priority", type: "select", options: opts(PRIORITIES) },
      { name: "subject", label: "Subject", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "status", label: "Status", type: "select", options: opts(TICKET_STATUSES) },
      { name: "assigneeId", label: "Assign to", type: "lookup", lookup: "users" },
      { name: "resolution", label: "Resolution", type: "textarea" },
    ],
    creatable: true,
    vendorCreatable: true,
    editable: true,
  },
  support: {
    key: "support",
    title: "Support",
    description: "Questions about payments, documents, and events.",
    api: "/api/tickets",
    permission: "tickets",
    statuses: opts(TICKET_STATUSES),
    columns: [
      { key: "number", label: "Ticket" },
      { key: "subject", label: "Subject" },
      { key: "category", label: "Category", kind: "status" },
      { key: "status", label: "Status", kind: "status" },
    ],
    fields: [
      { name: "category", label: "Category", type: "select", options: opts(TICKET_CATEGORIES), required: true },
      { name: "priority", label: "Priority", type: "select", options: opts(PRIORITIES) },
      { name: "subject", label: "Subject", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
    ],
    vendorCreatable: true,
  },
  users: {
    key: "users",
    title: "Users",
    description: "Super admin creates staff accounts here. Vendors are invited from Vendors with an email address.",
    api: "/api/users",
    permission: "users",
    columns: [
      { key: "name", label: "Name" },
      { key: "email", label: "Email" },
      { key: "portal", label: "Portal", kind: "status" },
      { key: "role.name", label: "Role" },
      { key: "status", label: "Status", kind: "status" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "email", label: "Email", type: "email", required: true },
      { name: "password", label: "Password", type: "text" },
      { name: "phone", label: "Phone", type: "text" },
      { name: "portal", label: "Portal", type: "select", options: ["ADMIN"], required: true },
      { name: "roleId", label: "Role", type: "lookup", lookup: "roles", required: true },
      { name: "status", label: "Status", type: "select", options: ["ACTIVE", "SUSPENDED"] },
    ],
    creatable: true,
    editable: true,
  },
  "audit-logs": {
    key: "audit-logs",
    title: "Audit log",
    description: "Who changed what, and when.",
    api: "/api/audit-logs",
    permission: "audit",
    columns: [
      { key: "createdAt", label: "When", kind: "date" },
      { key: "user.name", label: "User" },
      { key: "action", label: "Action" },
      { key: "module", label: "Module" },
      { key: "recordLabel", label: "Record" },
    ],
    fields: [],
  },
}

export function moduleByKey(key: string) {
  return modules[key]
}
